version: '3'

services:
    eyva_php:
        build: .docker/php
        container_name: eyva_php
        #        ports:
        #            - 5173:5173
        volumes:
            - .:/var/www:cached
        command: bash -c "service supervisor start && supervisorctl reread && supervisorctl update && supervisorctl start all & docker-php-entrypoint php-fpm"
        networks:
            - eyva

    eyva_nginx:
        image: nginx
        container_name: eyva_nginx
        ports:
            - "${FORWARD_NGINX_PORT:-8111}:80"
        volumes:
            - .:/var/www
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - eyva_php
        networks:
            - eyva

    eyva_db:
        image: mysql:8.1
        container_name: eyva_db
        #        ports:
        #            - 3306:3306
        volumes:
            - .docker/db/data:/var/lib/mysql
            - .docker/logs:/var/log/mysql
            - .docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
            - .docker/db/sql:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        networks:
            - eyva

    eyva_phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: eyva_phpmyadmin
        links:
            - eyva_db
        depends_on:
            - eyva_db
        ports:
            - "8112:80"
        environment:
            PMA_HOST: eyva_db
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        networks:
            - eyva

#    eyva_redis:
#        image: redis
#        container_name: eyva_redis
#        depends_on:
#            - eyva_php
#        environment:
#            REDIS_PASSWORD: ${REDIS_PASSWORD}
#        command: redis-server --requirepass ${REDIS_PASSWORD}
#        networks:
#            - eyva

networks:
    eyva:
